### ISSUE TITLE
Strings containing non-ascii characters should be unicode

### ISSUE THREAD

**Issue by jef-n** [qgispt/processing_pttransform#16]
Prefixing the string returned by [PTTransformProvider.getDescription](https://github.com/qgispt/processing_pttransform/blob/master/PTTransformProvider.py#L83) fixes [QGIS #12205](http://hub.qgis.org/issues/12205).  I suppose all strings containing non-ascii characters should be unicode.

**Comment by PedroVenancio** [comment]
Fixed in https://github.com/qgispt/processing_pttransform/commit/0d514093faa4a3a6beedfdb387c21cb7cdd07bf0
